image: paulushc/maven-jdk8-alpine

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s maven-settings.xml --batch-mode --errors --fail-at-end --show-version -DdmUser=$MAVEN_REPO_USER -DdmPass=$MAVEN_REPO_PASS -Dsonar.login=$SONAR_TOKEN -Dgpg.keyname=$REPO_GPGKEYNAME"

cache:
  paths:
    - .m2/repository

stages:
  - validate
  - test
  - build
  - artifact
  - deploy

before_script:
  - 'export GPG_TTY=$(tty)'
  - 'gpg --batch --import $GPG_PUB_FL'
  - 'gpg --batch --import $GPG_SEC_FL'
  - 'rm -rf maven-settings.xml'
  - 'echo $M2_FILE > maven-settings.xml'

validate:
  stage: validate
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS validate'
  except:
    - tags
  needs: []

compile:
  stage: validate
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS clean compile'
  except:
    - tags
  needs: ["validate"]

check-style:
  stage: validate
  script:
    - 'rm -rf target/site'
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS checkstyle:checkstyle'
  except:
    - tags
  artifacts:
    paths:
      - target/site/checkstyle.html
    expire_in: 4 days
  needs: ["compile"]

unit-test:
  stage: test
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS test'
  except:
    - tags
  needs: ["compile","check-style"]

integration-test:
  stage: test
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS verify -P integration-test'
  except:
    - tags
  needs: ["compile","check-style"]

coverage:
  stage: test
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS clean verify -P all-tests'
    - '[ -f target/site/jacoco/index.html ] && cat target/site/jacoco/index.html || echo "Total 0%"'
  except:
    - tags
  needs: ["unit-test","integration-test"]

qualitygate:
  stage: test
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS package'
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS sonar:sonar'
  except:
    - tags
  needs: ["unit-test","integration-test","coverage"]

build:
  stage: build
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS package'
  only:
    - master
  except:
    - tags
  needs: ["qualitygate"]

artifactory:
  stage: artifact
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS versions:set -DnewVersion="$CI_COMMIT_REF_NAME"'
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS versions:commit'
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS javadoc:jar javadoc:javadoc: source:jar deploy'
  only:
    - tags
  needs: ["build"]