name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Validate Code
        run: mvn -B validate --file pom.xml
      - name: Compile Code
        run: mvn -B clean compile --file pom.xml
      - name: Checkstyle
        run: mvn -B checkstyle:checkstyle -Dcheckstyle.skip=false --file pom.xml
      - name: Archive Checkstyle
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle
          path: target/site/checkstyle.html
          retention-days: 5
      - name: Unit Test
        run: mvn -B test --file pom.xml
      - name: Integration Test
        run: mvn -B verify -P integration-test --file pom.xml
      - name: Code Coverage
        run: mvn -B clean verify -P all-tests coveralls:report --file pom.xml
        env: # Or as an environment variable
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      - name: Qualitygate
        run: mvn -B clean verify package sonar:sonar --file pom.xml